apiVersion: v1
kind: Service
metadata:
  name: platforms-np-srv
spec:
  type: NodePort
  selector:
    app: platformservice
  ports:
    - name: platform-service
      protocol: TCP 
      port: 80 # the Node port
      targetPort: 80 # of the servise (container?)