apiVersion: apps/v1
kind: Deployment
metadata:
  name: platforms-depl
spec:
  replicas: 1 #number of instanses
  selector: # select a template
    matchLabels:
      app: platformservice
  template: #defime pod and container
    metadata:
      labels:
        app: platformservice
    spec:
      containers: # to run
        - name: platformservice # - array
          # image: binarythistle/platformservice:latest
          image: maksstep/platform-service:latest # docker img